export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      states: {
        Row: {
          id: string;
          name: string;
          code: string;
          capital: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          code: string;
          capital?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string;
          capital?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      districts: {
        Row: {
          id: string;
          state_id: string;
          name: string;
          code: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          state_id: string;
          name: string;
          code: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          state_id?: string;
          name?: string;
          code?: string;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      mandals: {
        Row: {
          id: string;
          district_id: string;
          name: string;
          code: string;
          mandal_type: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          district_id: string;
          name: string;
          code: string;
          mandal_type?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          district_id?: string;
          name?: string;
          code?: string;
          mandal_type?: string;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      villages: {
        Row: {
          id: string;
          mandal_id: string;
          name: string;
          code: string;
          ward: string | null;
          local_body: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          mandal_id: string;
          name: string;
          code: string;
          ward?: string | null;
          local_body?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          mandal_id?: string;
          name?: string;
          code?: string;
          ward?: string | null;
          local_body?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      data_sources: {
        Row: {
          id: string;
          name: string;
          department: string;
          source_type: 'REAL_OFFICIAL' | 'OPEN_DATA' | 'EXTERNAL_OPEN_DATA' | 'DEMONSTRATION' | 'MOCK_API';
          source_url: string | null;
          source_system: string | null;
          data_status: string;
          reliability_status: string;
          last_synchronized_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          department: string;
          source_type: 'REAL_OFFICIAL' | 'OPEN_DATA' | 'EXTERNAL_OPEN_DATA' | 'DEMONSTRATION' | 'MOCK_API';
          source_url?: string | null;
          source_system?: string | null;
          data_status?: string;
          reliability_status?: string;
          last_synchronized_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          department?: string;
          source_type?: 'REAL_OFFICIAL' | 'OPEN_DATA' | 'EXTERNAL_OPEN_DATA' | 'DEMONSTRATION' | 'MOCK_API';
          source_url?: string | null;
          source_system?: string | null;
          data_status?: string;
          reliability_status?: string;
          last_synchronized_at?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      parcels: {
        Row: {
          id: string;
          ulpin: string | null;
          parcel_reference: string | null;
          survey_number: string;
          subdivision_number: string | null;
          state_id: string;
          district_id: string;
          mandal_id: string;
          village_id: string;
          ward: string | null;
          local_body: string | null;
          area: number;
          area_unit: string;
          land_classification: string | null;
          land_use: string;
          geometry: unknown;
          centroid: unknown;
          source_id: string | null;
          source_record_id: string | null;
          data_status: string;
          verification_status: string;
          last_verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ulpin?: string | null;
          parcel_reference?: string | null;
          survey_number: string;
          subdivision_number?: string | null;
          state_id: string;
          district_id: string;
          mandal_id: string;
          village_id: string;
          ward?: string | null;
          local_body?: string | null;
          area: number;
          area_unit?: string;
          land_classification?: string | null;
          land_use?: string;
          geometry: unknown;
          centroid?: unknown;
          source_id?: string | null;
          source_record_id?: string | null;
          data_status?: string;
          verification_status?: string;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ulpin?: string | null;
          parcel_reference?: string | null;
          survey_number?: string;
          subdivision_number?: string | null;
          state_id?: string;
          district_id?: string;
          mandal_id?: string;
          village_id?: string;
          ward?: string | null;
          local_body?: string | null;
          area?: number;
          area_unit?: string;
          land_classification?: string | null;
          land_use?: string;
          geometry?: unknown;
          centroid?: unknown;
          source_id?: string | null;
          source_record_id?: string | null;
          data_status?: string;
          verification_status?: string;
          last_verified_at?: string | null;
          updated_at?: string;
        };
      };
      rights_records: {
        Row: {
          id: string;
          parcel_id: string;
          rights_holder_name: string;
          rights_holder_type: string;
          right_type: string;
          share: string | null;
          extent: string | null;
          possession_status: string;
          record_number: string | null;
          record_date: string | null;
          mutation_reference: string | null;
          source_id: string | null;
          source_record_id: string | null;
          verification_status: string;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          rights_holder_name: string;
          rights_holder_type?: string;
          right_type: string;
          share?: string | null;
          extent?: string | null;
          possession_status?: string;
          record_number?: string | null;
          record_date?: string | null;
          mutation_reference?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          rights_holder_name?: string;
          rights_holder_type?: string;
          right_type?: string;
          share?: string | null;
          extent?: string | null;
          possession_status?: string;
          record_number?: string | null;
          record_date?: string | null;
          mutation_reference?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      registration_records: {
        Row: {
          id: string;
          parcel_id: string;
          document_number: string;
          transaction_type: string;
          registration_date: string;
          execution_date: string | null;
          transaction_status: string;
          consideration_amount: number | null;
          stamp_duty: number | null;
          source_id: string | null;
          source_record_id: string | null;
          verification_status: string;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          document_number: string;
          transaction_type: string;
          registration_date: string;
          execution_date?: string | null;
          transaction_status?: string;
          consideration_amount?: number | null;
          stamp_duty?: number | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          document_number?: string;
          transaction_type?: string;
          registration_date?: string;
          execution_date?: string | null;
          transaction_status?: string;
          consideration_amount?: number | null;
          stamp_duty?: number | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      encumbrances: {
        Row: {
          id: string;
          parcel_id: string;
          encumbrance_type: string;
          reference_number: string | null;
          start_date: string | null;
          release_date: string | null;
          status: string;
          description: string | null;
          source_id: string | null;
          source_record_id: string | null;
          verification_status: string;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          encumbrance_type: string;
          reference_number?: string | null;
          start_date?: string | null;
          release_date?: string | null;
          status?: string;
          description?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          encumbrance_type?: string;
          reference_number?: string | null;
          start_date?: string | null;
          release_date?: string | null;
          status?: string;
          description?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      planning_records: {
        Row: {
          id: string;
          parcel_id: string;
          zoning: string;
          master_plan_zone: string | null;
          permitted_land_use: string | null;
          development_restrictions: string | null;
          road_reservation: boolean;
          building_restrictions: string | null;
          planning_authority: string | null;
          effective_date: string | null;
          review_date: string | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          zoning?: string;
          master_plan_zone?: string | null;
          permitted_land_use?: string | null;
          development_restrictions?: string | null;
          road_reservation?: boolean;
          building_restrictions?: string | null;
          planning_authority?: string | null;
          effective_date?: string | null;
          review_date?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          zoning?: string;
          master_plan_zone?: string | null;
          permitted_land_use?: string | null;
          development_restrictions?: string | null;
          road_reservation?: boolean;
          building_restrictions?: string | null;
          planning_authority?: string | null;
          effective_date?: string | null;
          review_date?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      building_permissions: {
        Row: {
          id: string;
          parcel_id: string;
          permission_number: string;
          approval_status: string;
          approval_date: string | null;
          building_use: string | null;
          permitted_floors: number | null;
          permitted_height: number | null;
          height_unit: string;
          built_up_area: number | null;
          area_unit: string;
          authority: string | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          permission_number: string;
          approval_status?: string;
          approval_date?: string | null;
          building_use?: string | null;
          permitted_floors?: number | null;
          permitted_height?: number | null;
          height_unit?: string;
          built_up_area?: number | null;
          area_unit?: string;
          authority?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          permission_number?: string;
          approval_status?: string;
          approval_date?: string | null;
          building_use?: string | null;
          permitted_floors?: number | null;
          permitted_height?: number | null;
          height_unit?: string;
          built_up_area?: number | null;
          area_unit?: string;
          authority?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      property_tax_records: {
        Row: {
          id: string;
          parcel_id: string;
          assessment_number: string | null;
          assessment_year: string;
          assessed_value: number | null;
          tax_amount: number | null;
          paid_amount: number | null;
          outstanding_amount: number | null;
          payment_status: string;
          last_paid_date: string | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          assessment_number?: string | null;
          assessment_year: string;
          assessed_value?: number | null;
          tax_amount?: number | null;
          paid_amount?: number | null;
          outstanding_amount?: number | null;
          payment_status?: string;
          last_paid_date?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          assessment_number?: string | null;
          assessment_year?: string;
          assessed_value?: number | null;
          tax_amount?: number | null;
          paid_amount?: number | null;
          outstanding_amount?: number | null;
          payment_status?: string;
          last_paid_date?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      utility_records: {
        Row: {
          id: string;
          parcel_id: string;
          electricity: boolean;
          water: boolean;
          drainage: boolean;
          sewerage: boolean;
          gas: boolean;
          road_access: boolean;
          telecom_fiber: boolean;
          provider: string | null;
          connection_id: string | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          electricity?: boolean;
          water?: boolean;
          drainage?: boolean;
          sewerage?: boolean;
          gas?: boolean;
          road_access?: boolean;
          telecom_fiber?: boolean;
          provider?: string | null;
          connection_id?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          electricity?: boolean;
          water?: boolean;
          drainage?: boolean;
          sewerage?: boolean;
          gas?: boolean;
          road_access?: boolean;
          telecom_fiber?: boolean;
          provider?: string | null;
          connection_id?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      restrictions: {
        Row: {
          id: string;
          parcel_id: string;
          restriction_type: string;
          description: string;
          authority: string;
          status: string;
          effective_date: string | null;
          expiry_date: string | null;
          review_date: string | null;
          affected_area: string | null;
          geometry: unknown | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          restriction_type: string;
          description: string;
          authority: string;
          status?: string;
          effective_date?: string | null;
          expiry_date?: string | null;
          review_date?: string | null;
          affected_area?: string | null;
          geometry?: unknown | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          restriction_type?: string;
          description?: string;
          authority?: string;
          status?: string;
          effective_date?: string | null;
          expiry_date?: string | null;
          review_date?: string | null;
          affected_area?: string | null;
          geometry?: unknown | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      parcel_documents: {
        Row: {
          id: string;
          parcel_id: string;
          document_type: string;
          document_reference: string | null;
          document_number: string | null;
          storage_path: string | null;
          file_name: string | null;
          file_size: number | null;
          mime_type: string | null;
          issuing_authority: string | null;
          issue_date: string | null;
          source_id: string | null;
          verification_status: string;
          is_demonstration: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          document_type: string;
          document_reference?: string | null;
          document_number?: string | null;
          storage_path?: string | null;
          file_name?: string | null;
          file_size?: number | null;
          mime_type?: string | null;
          issuing_authority?: string | null;
          issue_date?: string | null;
          source_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          document_type?: string;
          document_reference?: string | null;
          document_number?: string | null;
          storage_path?: string | null;
          file_name?: string | null;
          file_size?: number | null;
          mime_type?: string | null;
          issuing_authority?: string | null;
          issue_date?: string | null;
          source_id?: string | null;
          verification_status?: string;
          is_demonstration?: boolean;
          updated_at?: string;
        };
      };
      parcel_history: {
        Row: {
          id: string;
          parcel_id: string;
          event_type: string;
          event_date: string;
          description: string;
          reference: string | null;
          source_id: string | null;
          source_record_id: string | null;
          is_demonstration: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          event_type: string;
          event_date: string;
          description: string;
          reference?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          event_type?: string;
          event_date?: string;
          description?: string;
          reference?: string | null;
          source_id?: string | null;
          source_record_id?: string | null;
          is_demonstration?: boolean;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: 'citizen' | 'revenue_officer' | 'registration_officer' | 'planning_officer' | 'municipal_officer' | 'administrator';
          department: string | null;
          state_code: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: 'citizen' | 'revenue_officer' | 'registration_officer' | 'planning_officer' | 'municipal_officer' | 'administrator';
          department?: string | null;
          state_code?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: 'citizen' | 'revenue_officer' | 'registration_officer' | 'planning_officer' | 'municipal_officer' | 'administrator';
          department?: string | null;
          state_code?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          user_email: string | null;
          user_role: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          details: unknown | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          details?: unknown | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          user_email?: string | null;
          user_role?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          details?: unknown | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      service_requests: {
        Row: {
          id: string;
          parcel_id: string | null;
          citizen_user_id: string | null;
          citizen_email: string;
          service_type: string;
          description: string | null;
          status: string;
          assigned_department: string | null;
          assigned_role: string | null;
          priority: string;
          resolution_notes: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id?: string | null;
          citizen_user_id?: string | null;
          citizen_email: string;
          service_type: string;
          description?: string | null;
          status?: string;
          assigned_department?: string | null;
          assigned_role?: string | null;
          priority?: string;
          resolution_notes?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string | null;
          citizen_user_id?: string | null;
          citizen_email?: string;
          service_type?: string;
          description?: string | null;
          status?: string;
          assigned_department?: string | null;
          assigned_role?: string | null;
          priority?: string;
          resolution_notes?: string | null;
          resolved_at?: string | null;
          updated_at?: string;
        };
      };
      service_request_updates: {
        Row: {
          id: string;
          request_id: string;
          old_status: string | null;
          new_status: string;
          updated_by_user_id: string | null;
          updated_by_email: string | null;
          updated_by_role: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          old_status?: string | null;
          new_status: string;
          updated_by_user_id?: string | null;
          updated_by_email?: string | null;
          updated_by_role?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          old_status?: string | null;
          new_status?: string;
          updated_by_user_id?: string | null;
          updated_by_email?: string | null;
          updated_by_role?: string | null;
          notes?: string | null;
        };
      };
      change_detections: {
        Row: {
          id: string;
          parcel_id: string;
          change_type: string;
          previous_date: string | null;
          current_date: string | null;
          confidence_score: number | null;
          evidence_description: string | null;
          is_demonstration: boolean;
          data_source: string;
          review_status: string;
          reviewer_id: string | null;
          reviewer_email: string | null;
          review_notes: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parcel_id: string;
          change_type: string;
          previous_date?: string | null;
          current_date?: string | null;
          confidence_score?: number | null;
          evidence_description?: string | null;
          is_demonstration?: boolean;
          data_source?: string;
          review_status?: string;
          reviewer_id?: string | null;
          reviewer_email?: string | null;
          review_notes?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string;
          change_type?: string;
          previous_date?: string | null;
          current_date?: string | null;
          confidence_score?: number | null;
          evidence_description?: string | null;
          is_demonstration?: boolean;
          data_source?: string;
          review_status?: string;
          reviewer_id?: string | null;
          reviewer_email?: string | null;
          review_notes?: string | null;
          reviewed_at?: string | null;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          notification_type: string;
          title: string;
          message: string;
          entity_type: string | null;
          entity_id: string | null;
          is_read: boolean;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          notification_type: string;
          title: string;
          message: string;
          entity_type?: string | null;
          entity_id?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          notification_type?: string;
          title?: string;
          message?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          is_read?: boolean;
          read_at?: string | null;
        };
      };
      ai_analysis_log: {
        Row: {
          id: string;
          parcel_id: string | null;
          model_name: string;
          model_version: string | null;
          analysis_type: string;
          input_summary: string | null;
          output_result: unknown | null;
          confidence_score: number | null;
          is_demonstration: boolean;
          explanation: string | null;
          reviewed_by: string | null;
          review_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          parcel_id?: string | null;
          model_name: string;
          model_version?: string | null;
          analysis_type: string;
          input_summary?: string | null;
          output_result?: unknown | null;
          confidence_score?: number | null;
          is_demonstration?: boolean;
          explanation?: string | null;
          reviewed_by?: string | null;
          review_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          parcel_id?: string | null;
          model_name?: string;
          model_version?: string | null;
          analysis_type?: string;
          input_summary?: string | null;
          output_result?: unknown | null;
          confidence_score?: number | null;
          is_demonstration?: boolean;
          explanation?: string | null;
          reviewed_by?: string | null;
          review_status?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_ulpin: {
        Args: {
          p_state_code: string;
          p_district_code: string;
          p_mandal_code: string;
          p_village_code: string;
          p_sequence: number;
        };
        Returns: string;
      };
      update_parcel_centroid: {
        Args: Record<string, never>;
        Returns: unknown;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
